# =================== CONFIGURACIONES GLOBALES =====================

# ==== CONFIGURACION DE LA APLICACION ====
VERSION_CLIENTE = "1.0.0"
VERSION_SERVIDOR = "1.0.0"

# ==== CONFIGURACION DE RED ====
IP_SERVIDOR = "127.0.0.1"
PUERTO_SERVIDOR = 8080
TIMEOUT_CONEXION = 15  # Tiempo de espera para conexiones (segundos)
TIMEOUT_RESPUESTA = 15
TIEMPO_ESPERA = 10
BUFFER_SIZE = 1024
MAX_CLIENTES_EN_COLA = 10

# ==== CONFIGURACION DE SEGURIDAD ====
MAX_INTENTOS_LOGIN = 3
LONGITUD_MAX_NIP = 4

# ==== CONFIGURACION DE CUENTAS Y TARJETAS ====
TIPOS_TARJETA = ["DEBITO", "CREDITO"]
TIPOS_CUENTA = ["ESTANDAR", "PREMIUM"]

# Límites de saldo
SALDO_INICIAL_MINIMO = 100.0
SALDO_LIMITE_ESTANDAR = None  # Definir según reglas del negocio
SALDO_LIMITE_PREMIUM = None

# Tarjetas
LIMITE_TARJETA_DEBITO = None  # Definir según reglas del negocio
LIMITE_TARJETA_CREDITO_BASE = None

# ==== LIMITES DE OPERACIONES ====

# Límites diarios
LIMITE_DEPOSITO_DIARIO = 100_000.0
LIMITE_RETIRO_DIARIO = 10_000.0
LIMITE_TRANSFERENCIA_DIARIO = 40_000.0

# Límites por operación
DEPOSITO_MAXIMO = 100_000.0
DEPOSITO_MINIMO = 200.0

RETIRO_MAXIMO = 15_000.0
RETIRO_MINIMO = 100.0

TRANSFERENCIA_MAXIMA = 50_000.0
TRANSFERENCIA_MINIMA = 20.0

# Intereses
TASA_INTERES = 0.12

# MAX_HILOS_SERVIDOR = 10  # Puedes descomentar si usas concurrencia
